// List of 100 fantasy-themed game names
const fantasyGameNames = [
    "Mystic Realms",
    "Dragon's Lair",
    "Enchanted Quest",
    "Wizards of Arcana",
    "Shadow Kingdom",
    "Elven Legacy",
    "Forgotten Spells",
    "Crystal Chronicles",
    "Mythic Legends",
    "Realm of Titans",
    "Sorcerer's Path",
    "Fae Wilderness",
    "Ancient Runes",
    "Dragonfire",
    "Celestial Kingdoms",
    "Mage's Journey",
    "Phantom Gates",
    "Twilight Guardians",
    "Ethereal Dominion",
    "Arcane Odyssey",
    "Mystic Forge",
    "Valiant Hearts",
    "Emerald Dynasty",
    "Obsidian Tower",
    "Crimson Spire",
    "Astral Voyage",
    "Frostbound Realms",
    "Phoenix Rising",
    "Thunderstrike Saga",
    "Moonlight Crusade",
    "Starfall Legacy",
    "Dwarven Halls",
    "Orc Uprising",
    "Goblin's Gold",
    "Troll Hunter",
    "Unicorn Valley",
    "Griffin's Flight",
    "Centaur Plains",
    "Minotaur's Maze",
    "Kraken's Deep",
    "Hydra's Lair",
    "Chimera's Roar",
    "Basilisk Eye",
    "Wyvern's Peak",
    "Pegasus Wings",
    "Mermaid Cove",
    "Siren's Call",
    "Vampire's Castle",
    "Werewolf Moon",
    "Ghost Whispers",
    "Banshee's Cry",
    "Wraith Walker",
    "Lich Kingdom",
    "Party of Necromancers",
    "Paladin's Oath",
    "Cleric's Blessing",
    "Ranger's Trail",
    "Barbarian Saga",
    "Bard's Tale",
    "Rogue's Fortune",
    "Monk's Journey",
    "Druid's Grove",
    "Warlock's Pact",
    "Alchemist's Brew",
    "Summoner's Circle",
    "Enchanter's Illusion",
    "Diviner's Vision",
    "Conjurer's Trick",
    "Illusionist's Dream",
    "Abjurer's Shield",
    "Transmuter's Touch",
    "Evocation Storm",
    "Time Wanderer",
    "Pyromancer's Flame",
    "Frost Kingdom",
    "Earth's Echoes",
    "Windswept Realms",
    "Ocean's Depths",
    "Shadow Realm",
    "Light's Dominion",
    "Void Passage",
    "Wanderer's Path",
    "Spell Weaving",
    "Rune Mysteries",
    "Soul Binding",
    "Dream Shaping",
    "Storm Calling",
    "Earth Shaking",
    "Flame Keeping",
    "Frost Binding",
    "Star Gazing",
    "Moon Chasing",
    "Sun Seeking",
    "Wind Riding",
    "Stone Heart Journey",
    "Iron Forging",
    "Golden Hands",
];

export default fantasyGameNames;
