name: Deploy to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"

            - name: Install dependencies
              run: |
                  cd server
                  npm install

            - name: Install client dependencies
              run: |
                  cd client
                  npm install

            - name: Build project
              run: |
                  cd server
                  npm run build

            - name: Create .env file
              env:
                  # App Vars
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
                  MONGO_USER: ${{ secrets.MONGO_USER }}
                  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
                  PORT: ${{ vars.PORT }}
                  MONGO_URI: ${{ vars.MONGO_URI }}
                  NODE_ENV: ${{ vars.NODE_ENV }}
                  FROM_EMAIL: ${{ vars.FROM_EMAIL }}
              run: |
                  echo "JWT_SECRET=$JWT_SECRET" > .env
                  echo "RESEND_API_KEY=$RESEND_API_KEY" >> .env
                  echo "MONGO_USER=$MONGO_USER" >> .env
                  echo "MONGO_PASSWORD=$MONGO_PASSWORD" >> .env
                  echo "PORT=$PORT" >> .env
                  echo "MONGO_URI=$MONGO_URI" >> .env
                  echo "NODE_ENV=$NODE_ENV" >> .env
                  echo "FROM_EMAIL=$FROM_EMAIL" >> .env
                  echo ".env file created with required variables:"
                  cat .env

            - name: Prepare server directories
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SERVER_HOST: ${{ secrets.SERVER_HOST }}
                  SERVER_PATH: ${{ secrets.SERVER_PATH }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh -o StrictHostKeyChecking=no $SERVER_HOST "mkdir -p $SERVER_PATH/releases && mkdir -p $SERVER_PATH/current"

            - name: Deploy to server
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SERVER_HOST: ${{ secrets.SERVER_HOST }}
                  SERVER_PATH: ${{ secrets.SERVER_PATH }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa

                  # Use GITHUB_RUN_NUMBER as the build number
                  BUILD_NUMBER=${{ github.run_number }}
                  TEMP_DEPLOY_DIR="$SERVER_PATH/releases/$BUILD_NUMBER"

                  # Verify .env file exists before rsync
                  ls -la .env

                  # Explicitly include .env in the rsync command
                  rsync -av --exclude-from=.rsyncignore -e "ssh -o StrictHostKeyChecking=no" ./ $SERVER_HOST:$TEMP_DEPLOY_DIR

                  # Verify .env was transferred to the server
                  ssh -o StrictHostKeyChecking=no $SERVER_HOST "ls -la $TEMP_DEPLOY_DIR/.env"

                  # Update the current symlink
                  ssh -o StrictHostKeyChecking=no $SERVER_HOST "ln -sfn $TEMP_DEPLOY_DIR $SERVER_PATH/current && cd $SERVER_PATH/current && npm install && pm2 reload ecosystem.config.js"

                  # Cleanup old releases
                  ssh -o StrictHostKeyChecking=no $SERVER_HOST "cd $SERVER_PATH/releases && ls -t | tail -n +6 | xargs rm -rf"
